import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../server/store.ts';
test('actual local SQLite persists interest, independent Hidden intention, exact review, preferences and feedback after close/reopen',()=>{const directory=mkdtempSync(join(tmpdir(),'town-preview-test-'));try{const path=join(directory,'preview.sqlite');let s=new Store(path);const token=s.beginScan();s.ingest('prcr','BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nUID:persistent\nSUMMARY:Science night\nDTSTART:20261205T150000Z\nEND:VEVENT\nEND:VCALENDAR','persist','2026-10-04T02:35:33.636296Z','archived',token.fence);s.endScan(token.fence);const item=s.snapshot().items[0];s.action(item.id,'interested',true);s.action(item.id,'hidden',true);s.action(item.id,'review',{version:item.version,changeIds:[]});s.action(item.id,'feedback','less');s.updateSettings({...s.settings(),fallSaturdays:false});s.db.close();s=new Store(path);const restored=s.snapshot().items[0];assert.equal(restored.interested,true);assert.equal(restored.hidden,true);assert.equal(restored.unread,false);assert.equal(s.settings().fallSaturdays,false);assert.equal(s.db.prepare('SELECT count(*) n FROM feedback').get()!.n,1);s.action(item.id,'hidden',false);assert.equal(s.snapshot().items[0].interested,true);s.db.close();}finally{rmSync(directory,{recursive:true,force:true});}});

test('public starter defaults are neutral while configured local priorities survive reopen',()=>{const directory=mkdtempSync(join(tmpdir(),'town-neutral-settings-'));try{const path=join(directory,'preview.sqlite');let store=new Store(path);const initial=store.settings();assert.equal(initial.birthDate,null);assert.equal(initial.fallSaturdays,false);assert.equal(Object.values(initial.weights).every(weight=>weight===0),true);const configured={...initial,fallSaturdays:true,weights:{...initial.weights,science:3,art:9}};store.updateSettings(configured);store.db.close();store=new Store(path);assert.deepEqual(store.settings(),configured);store.db.close();}finally{rmSync(directory,{recursive:true,force:true});}});

test('partial preference updates preserve omitted values and reject non-boolean schedule rules atomically',()=>{const store=new Store(':memory:');try{store.updateSettings({weights:{science:3}});assert.equal(store.settings().fallSaturdays,false);store.updateSettings({fallSaturdays:true,weights:{art:9}});store.updateSettings({weights:{science:4}});assert.equal(store.settings().fallSaturdays,true);assert.equal(store.settings().weights.art,9);assert.equal(store.settings().weights.science,4);const before=store.settings();for(const fallSaturdays of ['false',0,null])assert.throws(()=>store.updateSettings({fallSaturdays,weights:{art:1}}),/true or false/);assert.deepEqual(store.settings(),before);}finally{store.db.close();}});
