import {createServer,type IncomingMessage,type ServerResponse} from 'node:http';
import {readFileSync,mkdirSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {createServer as createVite} from 'vite';
import {Store} from './store.ts';
import {PARTS,type Part} from '../src/domain.ts';
const port=Number(process.env.PORT??4173);const origin=`http://127.0.0.1:${port}`;
mkdirSync(new URL('../data/',import.meta.url),{recursive:true});const store=new Store(new URL('../data/preview.sqlite',import.meta.url).pathname);
const capturedAt='2026-10-04T02:35:33.636296Z';
async function fixtures(){const token=store.beginScan();try{for(const part of Object.keys(PARTS) as Part[])store.ingest(part,readFileSync(new URL(`../fixtures/${part}.ics`,import.meta.url),'utf8'),`initial-fixture-${part}`,capturedAt,'archived',token.fence);}finally{store.endScan(token.fence);}}
if(store.snapshot().items.length===0)await fixtures();
store.reparseLatest('1.1');
let scanning=false;let lastScan:any=null;
async function scan(){if(scanning)throw Error('Scan already in progress.');const token=store.beginScan();scanning=true;const results=[];try {for(const part of Object.keys(PARTS) as Part[]){try{const response=await fetch(PARTS[part].url,{redirect:'error',signal:AbortSignal.timeout(15_000),headers:{Accept:'text/calendar','User-Agent':'HomeschoolCollector-LocalPreview/0.1 (ordinary public calendar check)'}});if(!response.ok)throw Error(`HTTP ${response.status}; request stopped, no bypass attempted.`);const size=Number(response.headers.get('content-length')??0);if(size>2_000_000)throw Error('Response exceeds 2 MB limit.');const reader=response.body?.getReader();let bytes=0;const chunks:Uint8Array[]=[];if(!reader)throw Error('No calendar response body.');while(true){const r=await reader.read();if(r.done)break;bytes+=r.value.byteLength;if(bytes>2_000_000){await reader.cancel();throw Error('Response exceeds 2 MB limit.');}chunks.push(r.value);}const body=Buffer.concat(chunks).toString('utf8');const observedAt=new Date().toISOString();const receipt=store.ingest(part,body,randomUUID(),observedAt,'live',token.fence);results.push({part,ok:true,receipt});}catch(e){const error=(e as Error).message;store.failure(part,error,token.fence);results.push({part,ok:false,error});}}lastScan={finishedAt:new Date().toISOString(),results};return lastScan;}finally{store.endScan(token.fence);scanning=false;}}
function send(res:ServerResponse,status:number,data:any){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data));}
async function body(req:IncomingMessage){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>32_000)throw Error('Request too large.');}return JSON.parse(raw||'{}');}
const vite=await createVite({server:{middlewareMode:true,host:'127.0.0.1',allowedHosts:['127.0.0.1','localhost'],hmr:{port:port+1,host:'127.0.0.1'}},appType:'spa'});
const app=createServer(async(req,res)=>{const host=req.headers.host;if(host!==`127.0.0.1:${port}`&&host!==`localhost:${port}`){send(res,403,{error:'Loopback host required.'});return;}if(!['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress??'')){send(res,403,{error:'Loopback connection required.'});return;}if(req.url?.startsWith('/api/')){const allowed=[origin,`http://localhost:${port}`];if((req.headers.origin&&!allowed.includes(req.headers.origin))||req.headers['sec-fetch-site']==='cross-site'){send(res,403,{error:'Same-origin access required.'});return;}if(req.method==='POST'&&(!req.headers.origin||!allowed.includes(req.headers.origin)||!req.headers['content-type']?.startsWith('application/json'))){send(res,403,{error:'Same-origin JSON mutation required.'});return;}try{const route=req.url.split('?')[0];if(req.method==='GET'&&route==='/api/snapshot'){send(res,200,{...store.snapshot(),scanning,lastScan});return;}if(req.method==='POST'&&route==='/api/scan'){send(res,200,await scan());return;}if(req.method==='POST'&&route==='/api/action'){const b=await body(req);store.action(b.id,b.action,b.value);send(res,200,{ok:true});return;}if(req.method==='POST'&&route==='/api/decision'){send(res,200,store.decision(await body(req)));return;}if(req.method==='POST'&&route==='/api/settings'){send(res,200,store.updateSettings(await body(req)));return;}send(res,404,{error:'Unknown route.'});}catch(e){send(res,400,{error:(e as Error).message});}return;}res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Content-Type-Options','nosniff');vite.middlewares(req,res,()=>{res.writeHead(404);res.end();});});
app.listen(port,'127.0.0.1',()=>console.log(`Town events local preview: ${origin}`));
// Exactly one ordinary two-part source check on first startup; saved results are reused on later starts.
if(store.snapshot().sources.every(s=>s.kind==='archived'&&s.health==='ok'))scan().then(r=>console.log('Initial ordinary source check:',JSON.stringify(r))).catch(e=>console.log('Initial scan unavailable:',e.message));
