import ICAL from 'ical.js';
export const PUBLISHER='town:fuquay-varina';
export const PARTS={prcr:{name:'Parks, Recreation & Cultural Resources',url:'https://www.fuquay-varina.org/common/modules/iCalendar/iCalendar.aspx?feed=calendar&catID=23'},arts:{name:'Arts Center',url:'https://www.fuquay-varina.org/common/modules/iCalendar/iCalendar.aspx?feed=calendar&catID=45'}};
export type Part=keyof typeof PARTS;
export interface Time {kind:'known'|'all-day'|'unknown'; local:string|null; instant:string|null; zone:string|null;}
export interface Opportunity {id:string;uid:string;title:string;description:string;location:string;start:Time;end:Time;status:string;detailUrl:string|null;closure:boolean;recurring:boolean;timeWarnings:string[];sourceStampWarnings:string[];}
export interface Settings {birthDate:string|null;fallSaturdays:boolean;weights:Record<string,number>}
// Public starter defaults are neutral. Personal settings are persisted only in the local database.
export const defaults:Settings={birthDate:null,fallSaturdays:false,weights:{sailing:0,chess:0,science:0,outdoors:0,education:0,'hands-on':0,art:0,craft:0}};
export const plain=(v:unknown)=>String(v??'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').trim();
export function safeUrl(value:string):string|null {try {const u=new URL(value);return u.protocol==='https:'&&u.hostname==='www.fuquay-varina.org'&&!u.username&&!u.password&&!u.port&&((u.pathname==='/calendar.aspx'&&/^\d+$/.test(u.searchParams.get('EID')??''))||/^\/m\/calendar\/event\/detail\/\d+$/.test(u.pathname))?u.href:null;} catch{return null;}}
function time(prop:ICAL.Property|null,warnings:string[]):Time {if(!prop)return {kind:'unknown',local:null,instant:null,zone:null};try {const t=prop.getFirstValue() as ICAL.Time;const tz=prop.getParameter('tzid');if(t.isDate)return {kind:'all-day',local:t.toString(),instant:null,zone:null};const zone=t.zone?.tzid;if(!tz&&zone!=='UTC'){warnings.push('Clock time has no timezone; needs checking.');return {kind:'unknown',local:t.toString(),instant:null,zone:null};}if(tz&&t.zone===ICAL.Timezone.localTimezone){warnings.push('Unsupported timezone.');return {kind:'unknown',local:t.toString(),instant:null,zone:String(tz)};}return {kind:'known',local:t.toString(),instant:t.toJSDate().toISOString(),zone:String(tz??'UTC')};}catch{warnings.push('Invalid source time.');return {kind:'unknown',local:null,instant:null,zone:null};}}
export function parseCalendar(body:string){if(body.length>2_000_000)throw Error('Calendar exceeds 2 MB limit.');if(!body.trimStart().startsWith('BEGIN:VCALENDAR')||!body.includes('END:VCALENDAR'))throw Error('Response is not a complete calendar.');ICAL.TimezoneService.reset();const root=new ICAL.Component(ICAL.parse(body));if(root.name!=='vcalendar')throw Error('Response is not a calendar.');for(const z of root.getAllSubcomponents('vtimezone')){const id=String(z.getFirstPropertyValue('tzid'));ICAL.TimezoneService.register(new ICAL.Timezone({component:z,tzid:id}),id);}const events:Opportunity[]=[],rejects:{index:number;reason:string}[]=[];const components=root.getAllSubcomponents('vevent');components.forEach((c,index)=>{try {const uid=String(c.getFirstPropertyValue('uid')??'').trim();if(!uid||uid.length>256)throw Error('Missing or invalid publisher UID.');if(c.hasProperty('recurrence-id'))throw Error('Recurrence exception unsupported; observation quarantined.');const title=plain(c.getFirstPropertyValue('summary'));if(!title)throw Error('Missing event title.');const warnings:string[]=[],stamps:string[]=[];for(const p of ['dtstamp','last-modified']){const value=c.getFirstProperty(p);if(value&&!value.toICALString().endsWith('Z'))stamps.push(`${p.toUpperCase()} is source-local metadata, not a trusted update order.`);}const description=plain(c.getFirstPropertyValue('description'));const links=description.match(/https?:\/\/[^\s<>]+/g)??[];events.push({id:`${PUBLISHER}:${uid}`,uid,title,description,location:plain(c.getFirstPropertyValue('location')).replace(/^[-\s]+$/,''),start:time(c.getFirstProperty('dtstart'),warnings),end:time(c.getFirstProperty('dtend'),warnings),status:String(c.getFirstPropertyValue('status')??'unknown').toLowerCase(),detailUrl:links.map(safeUrl).find(Boolean)??null,closure:/\bclosed\b/i.test(title),recurring:c.hasProperty('rrule')||c.hasProperty('rdate')||c.hasProperty('exdate'),timeWarnings:warnings,sourceStampWarnings:stamps});}catch(e){rejects.push({index,reason:String((e as Error).message)});}});return {events,rejects,returned:components.length};}
export function semantic(o:Opportunity){return {title:o.title,description:o.description,location:o.location,start:o.start,end:o.end,status:o.status,detailUrl:o.detailUrl,closure:o.closure,recurring:o.recurring,timeWarnings:o.timeWarnings};}
export interface Rule {name:string;result:'pass'|'fail'|'unknown'|'not checked';reason:string}
export function assess(o:Opportunity,settings:Settings,now=new Date(),conflict=false){const rules:Rule[]=[];const start=o.start.instant?new Date(o.start.instant):null;const nyNow=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);const local=o.start.local?.slice(0,10);if(o.recurring)rules.push({name:'Attendance',result:'unknown',reason:'Event recurrence is unsupported; sessions need checking.'});if(o.recurring)rules.push({name:'Future attendance',result:'unknown',reason:'Recurrence master cannot prove future session availability.'});else if(o.start.kind==='all-day')rules.push({name:'Date',result:local&&local>nyNow?'pass':local===nyNow?'unknown':'fail',reason:'All-day event; end date is exclusive. Today’s remaining attendance needs checking.'});else rules.push({name:'Future attendance',result:start?start>now?'pass':o.end.instant&&new Date(o.end.instant)>now?'unknown':'fail':'unknown',reason:start?start>now?'Start is in the future.':'Already started; late entry is unverified.':'Clock time or timezone is unknown.'});const date=local?new Date(`${local}T12:00:00Z`):null;rules.push({name:'Fall Saturdays',result:!settings.fallSaturdays?'not checked':o.recurring?'unknown':date?date.getUTCDay()===6&&date.getUTCMonth()>=8&&date.getUTCMonth()<=10?'fail':'pass':'unknown',reason:settings.fallSaturdays?'September–November Saturdays excluded, using the event’s local date.':'Rule disabled.'});rules.push({name:'Age',result:'unknown',reason:settings.birthDate?'Provider age requirement and cutoff unverified.':'Age preference unset; provider eligibility unverified.'});rules.push({name:'Availability',result:o.status==='cancelled'?'fail':'unknown',reason:o.status==='cancelled'?'Explicitly cancelled.':'Registration, capacity, fee and eligibility need official confirmation.'});rules.push({name:'Travel / budget / calendar conflicts',result:'not checked',reason:'Not configured or connected.'});if(conflict)rules.push({name:'Source agreement',result:'unknown',reason:'Category feeds disagree; inspect both representations.'});if(o.recurring)rules.push({name:'Session dates',result:'unknown',reason:'No automatic occurrence eligibility for recurrence.'});const verdict=rules.some(r=>r.result==='fail')?'ineligible':rules.some(r=>r.result==='unknown')?'needs checking':'passes configured rules';return {rules,verdict};}
const keywords:Record<string,RegExp>={sailing:/\bsail(?:ing|boat)?\b/i,chess:/\bchess\b/i,science:/\b(?:science|STEM|experiment|astronomy)\b/i,outdoors:/\b(?:outdoor|nature|hike|trail)\b/i,education:/\b(?:learn|learning|education|workshop)\b/i,'hands-on':/\b(?:hands.on|maker workshop|building workshop|making workshop)\b/i,art:/\b(?:art|arts|painting|drawing)\b/i,craft:/\bcrafts?\b/i};
export function relevance(o:Opportunity,settings:Settings){const text=`${o.title} ${o.description}`;const reasons=Object.entries(keywords).filter(([,r])=>r.test(text)).map(([key])=>({key,weight:settings.weights[key]??0,evidence:text.match(keywords[key])?.[0]??key}));return {score:reasons.filter(r=>!['education','hands-on','craft'].includes(r.key)).reduce((n,r)=>n+r.weight,0)+Math.min(8,reasons.filter(r=>['education','hands-on','craft'].includes(r.key)).reduce((n,r)=>n+r.weight,0)),reasons};}
