import React,{useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {PARTS,defaults} from './domain';
import {REASONS,CONCERN_DIMENSIONS,type ReasonCode} from './decisions';
import './style.css';
type Item=any;const tabs=['New','Changed','All upcoming','Interested','Passed','Reconsider','Hidden','Needs checking','Excluded by rules','Closures','Sources','Preferences'];
const zone='America/New_York';
const localToday=(stamp:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(stamp));
function dateTime(time:any){if(!time.local)return 'Time needs checking';if(time.kind==='all-day')return `${time.local} · All day`;if(!time.instant)return `${time.local} · Clock / timezone needs checking`;return new Intl.DateTimeFormat('en-US',{timeZone:zone,weekday:'short',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(time.instant))+' ET';}
const shortDate=(stamp:string)=>new Intl.DateTimeFormat('en-US',{timeZone:zone,month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(stamp));
function attendanceValue(field:string,value:any):string{
 if(value==null)return 'Not represented in this version';
 if(field==='start'||field==='end')return dateTime(value);
 if(field==='recurring')return value?'Unsupported recurring master · individual dates need checking':'Single nonrecurring event';
 if(field==='evidence')return `Start: ${dateTime(value.start)}; end: ${dateTime(value.end)}; status: ${value.status}; ${value.recurring?'unsupported recurring master':'single event'}`;
 return String(value);
}
async function api(path:string,data?:any){const r=await fetch(`/api/${path}`,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{cache:'no-store'});const result=await r.json();if(!r.ok)throw Error(result.error??'Request failed.');return result;}
function App(){const [snapshot,setSnapshot]=useState<any>(null),[tab,setTab]=useState('New'),[query,setQuery]=useState(''),[source,setSource]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[selected,setSelected]=useState<Item|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[settings,setSettings]=useState<any>(defaults);
 const preferenceDirty=useRef(false);
 const [reasonForm,setReasonForm]=useState<any>(null),[decisionBusy,setDecisionBusy]=useState(false),[decisionError,setDecisionError]=useState('');
 const submittingDecision=useRef(false),decisionCommandKeys=useRef(new Map<string,string>()),selectedRef=useRef<Item|null>(selected);selectedRef.current=selected;
 const [focusRequest,setFocusRequest]=useState<{itemId:string;sequence:number}|null>(null);
 useEffect(()=>{if(!focusRequest)return;if(selectedRef.current?.id===focusRequest.itemId)document.querySelector<HTMLElement>('#decision-heading')?.focus();else if(!selectedRef.current)(document.querySelector<HTMLElement>('.list-title h2')??document.querySelector<HTMLElement>('nav button.active'))?.focus();},[focusRequest]);
 async function load(){const s=await api('snapshot');setSnapshot(s);if(!preferenceDirty.current)setSettings(s.settings);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));const id=setInterval(()=>load().catch(()=>{}),15000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(!selected)return;const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector('.detail') as HTMLElement;const background=Array.from(document.querySelector('.app')!.children).filter(e=>!e.classList.contains('overlay')) as HTMLElement[];background.forEach(e=>e.inert=true);const focusable=()=>Array.from(dialog.querySelectorAll<HTMLElement>('button,a[href],input,select,textarea,[tabindex]')).filter(e=>!e.hasAttribute('disabled')&&e.offsetParent!==null);focusable()[0]?.focus();const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setSelected(null);}if(e.key==='Tab'){const list=focusable(),first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',keys);return()=>{background.forEach(e=>e.inert=false);document.removeEventListener('keydown',keys);if(previous?.isConnected)previous.focus();else (document.querySelector<HTMLElement>('.list-title h2')??document.querySelector<HTMLElement>('nav button.active'))?.focus();};},[selected?.id]);
 useEffect(()=>{if(!selected){setReasonForm(null);setDecisionError('');}},[selected?.id]);
 useEffect(()=>{if(reasonForm)document.querySelector<HTMLElement>('.reason-form input')?.focus();},[Boolean(reasonForm)]);
 useEffect(()=>{if(!snapshot)return;const pending=new Set<string>();const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;const id=(entry.target as HTMLElement).dataset.eventId;if(id&&!pending.has(id)){pending.add(id);api('action',{id,action:'surface'}).catch(()=>{});observer.unobserve(entry.target);}}},{threshold:0.2});document.querySelectorAll('[data-event-id]').forEach(element=>observer.observe(element));return()=>observer.disconnect();},[snapshot,tab,query,source,from,to]);
 async function action(item:Item,kind:string,value:any){try{await api('action',{id:item.id,action:kind,value});await load();if(kind==='review'){setSelected(null);setMessage('Reviewed the exact version and changes shown.');}else{setSelected((s:Item|null)=>s?.id===item.id?{...s,...(kind==='interested'||kind==='hidden'?{[kind]:value}:{})}:s);setMessage(kind==='feedback'?'Feedback saved. Preferences stay as configured.':'Saved.');}}catch(e){setMessage((e as Error).message);}}
 function showDetails(item:Item){setSelected(item);setReasonForm(null);setDecisionError('');}
 function openPass(item:Item){if(submittingDecision.current)return;setSelected(item);setDecisionError('');setReasonForm({reasons:[],dimensions:[],generalIntent:'listing',targetId:'',targetScope:'child',note:'',commandKey:crypto.randomUUID()});}
 async function decide(item:Item,actionKind:string,form?:any){
  if(submittingDecision.current)return;submittingDecision.current=true;setDecisionBusy(true);if(selectedRef.current?.id===item.id)setDecisionError('');
  const retryIdentity=`${item.id}:${actionKind}:${item.decision.active?.decision_id??'none'}:${item.version}`;if(!form&&!decisionCommandKeys.current.has(retryIdentity))decisionCommandKeys.current.set(retryIdentity,crypto.randomUUID());
  try{const payload={id:item.id,action:actionKind,shownVersion:item.version,expectedActiveDecisionId:item.decision.active?.decision_id??null,targetDecisionId:actionKind==='pass'?null:item.decision.active?.decision_id,...snapshot.localScope,...(form??{}),commandKey:form?.commandKey??decisionCommandKeys.current.get(retryIdentity)};const result=await api('decision',payload);const latest=await api('snapshot');setSnapshot(latest);const current=latest.items.find((i:Item)=>i.id===item.id);setSelected((shown:Item|null)=>shown?.id===item.id?{...shown,decision:current.decision,passed:current.passed,currentVersion:current.version}:shown);const sameDialog=selectedRef.current?.id===item.id;if(sameDialog)setReasonForm(null);if(sameDialog||!selectedRef.current)setFocusRequest({itemId:item.id,sequence:Date.now()});decisionCommandKeys.current.delete(retryIdentity);setMessage(actionKind==='pass'?'Passed with your reasons. Ranking, bookmarks and source reviews are unchanged.':actionKind==='undo'?'Decision undone. Bookmarks and source review history are unchanged.':'Reconsideration marked seen; source warnings remain separate.');if(result.staleAtSubmit&&sameDialog)setDecisionError('Your decision is tied to the version you saw. Newer source facts exist; inspect the current listing before a new decision.');}
  catch(e){if(selectedRef.current?.id===item.id)setDecisionError((e as Error).message);else setMessage((e as Error).message);}finally{submittingDecision.current=false;setDecisionBusy(false);}
 }
 async function refresh(){setBusy(true);setMessage('Checking the two public Town feeds…');try{const r=await api('scan',{});await load();setMessage(r.results.every((p:any)=>p.ok)?'Source check finished. Coverage remains unknown.':'Source check finished with failures. Last-known results retained.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(!snapshot)return <main className="loading">Loading local collection…<p>{message}</p></main>;
 const latestSelectedVersion=selected?snapshot.items.find((i:Item)=>i.id===selected.id)?.version??selected.version:0;
 const items=snapshot.items as Item[];const attention=items.filter(i=>i.notices.length||i.decision.reconsider?.primary),otherReconsider=items.filter(i=>i.decision.reconsider&&!i.decision.reconsider.primary);const unread=items.filter(i=>!i.hidden&&!i.closure&&i.status!=='cancelled'&&i.verdict!=='ineligible'&&i.unread&&!i.passed).length;
 let visible=items.filter(i=>tab==='Closures'?i.closure:tab==='Hidden'?i.hidden:tab==='Interested'?i.interested:tab==='Passed'?i.passed:tab==='Reconsider'?Boolean(i.decision.reconsider):tab==='Changed'?i.changes.some((c:any)=>!c.ack_at):!i.hidden&&!i.closure&&i.status!=='cancelled');if(tab==='New')visible=visible.filter(i=>i.unread&&!i.passed&&i.verdict!=='ineligible');if(tab==='Excluded by rules')visible=visible.filter(i=>i.verdict==='ineligible');if(tab==='Needs checking')visible=visible.filter(i=>i.verdict==='needs checking');if(tab==='All upcoming')visible=visible.filter(i=>!i.start.local||i.recurring||i.start.local.slice(0,10)>=localToday(snapshot.serverTime));visible=visible.filter(i=>(source==='all'||i.memberships.includes(source))&&(!from||!i.start.local||i.start.local.slice(0,10)>=from)&&(!to||!i.start.local||i.start.local.slice(0,10)<=to)&&`${i.title} ${i.description} ${i.location}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="app"><header><div><span className="eyebrow">LOCAL · PUBLIC EVENTS PREVIEW</span><h1>Town events<span className="period">.</span></h1><p>A small inbox for discoveries and changes.</p></div><button className="primary" disabled={busy||snapshot.scanning} onClick={refresh}>{busy||snapshot.scanning?'Checking sources…':'Check sources'}</button></header>
 <section className="scope"><strong>Initial collection</strong><span>{snapshot.counts.identities} publisher identities · {snapshot.counts.memberships} category memberships · {snapshot.counts.closures} closures</span><p>Town calendar coverage unknown. Classes and camps are not connected. Age, fees and availability need checking.</p></section>
 <nav aria-label="Inbox views">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>{setTab(t);setSelected(null);setReasonForm(null);}} key={t}>{t}{t==='New'&&unread>0?<span className="count">{unread}</span>:t==='Passed'?<span className="count">{items.filter(i=>i.passed).length}</span>:t==='Reconsider'?<span className="count">{items.filter(i=>i.decision.reconsider).length}</span>:null}</button>)}</nav>
 {message&&<div className="message" role="status">{message}<button aria-label="Dismiss message" onClick={()=>setMessage('')}>×</button></div>}
 {attention.length>0&&<section className="notices"><h2>Changes that need attention</h2><p>Important source warnings and timing reconsiderations stay separate from a pass or source review.</p>{attention.map(item=><button key={item.id} onClick={()=>showDetails(item)}>{item.title}<span>{item.notices.length?`${item.notices.length} source warning${item.notices.length===1?'':'s'} · `:''}{item.decision.reconsider?.primary?'Timing changed · ':''}Inspect →</span></button>)}</section>}
 {otherReconsider.length>0&&<section className="other-changes"><h2>Other attendance changes <span className="count">{otherReconsider.length}</span></h2><p>These items remain passed for general-interest reasons. Earlier timing evidence is retained.</p>{otherReconsider.map(item=><button key={item.id} onClick={()=>showDetails(item)}>{item.title} · Inspect changes →</button>)}</section>}
 {tab==='Sources'?<section className="sources"><h2>Source health</h2><p>Last-known records survive failed checks. Missing feed rows are not inferred to be cancellations.</p>{snapshot.sources.map((s:any)=><article key={s.id}><h3>{PARTS[s.id as keyof typeof PARTS].name}</h3><span className="badge">{s.health}</span><dl><dt>Evidence</dt><dd>{s.kind==='live'?'Current local retrieval':s.kind==='archived'?'Archived public calendar':'No successful retrieval'}</dd><dt>Last successful observation</dt><dd>{s.observed_at?shortDate(s.observed_at)+' ET':'None'}</dd><dt>Latest attempt</dt><dd>{s.attempted_at?shortDate(s.attempted_at)+' ET':'None'}</dd><dt>Coverage / horizon</dt><dd>Unknown; response processing does not prove source completeness.</dd></dl>{s.error&&<p className="error">{s.error}</p>}</article>)}<h3>Recent intake receipts</h3>{snapshot.receipts.map((r:any)=><p key={r.batchId}>{PARTS[r.part as keyof typeof PARTS].name}: {r.returned} returned · {r.accepted} accepted · {r.rejected.length} rejected · {r.kind}</p>)}<p className="footnote">Only local retrieval is tested here. No hosted schedule, D1 deployment, calendar export or Muse integration is connected.</p></section>:tab==='Preferences'?<section className="preferences"><h2>Your preferences</h2><p>Ranking uses matching source words, with the weights below. Generic education, hands-on and craft bonuses are capped at 8 combined. Reason-aware passes record your intent without changing ranking in this phase. Earlier More / Less remains unscoped historical feedback.</p><label className="checkbox"><input type="checkbox" checked={settings.fallSaturdays} onChange={e=>{preferenceDirty.current=true;setSettings({...settings,fallSaturdays:e.target.checked});}}/> Exclude September–November Saturdays</label>{Object.keys(defaults.weights).map(k=><label className="weight" key={k}><span>{k}</span><input type="range" min="0" max="10" value={settings.weights[k]} onChange={e=>{preferenceDirty.current=true;setSettings({...settings,weights:{...settings.weights,[k]:Number(e.target.value)}});}}/><output>{settings.weights[k]}</output></label>)}<p>Age, travel, budget, calendar conflicts and course preferences: not configured. Provider age cutoff validation remains open.</p><button className="primary" onClick={async()=>{try{await api('settings',settings);preferenceDirty.current=false;await load();setMessage('Preferences saved. Ranking updated; review history retained.');}catch(e){setMessage((e as Error).message);}}}>Save preferences</button></section>:<>
 <section className="filters" aria-label="Filter events"><label>Search<input type="search" placeholder="Title, description or place" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Category<select value={source} onChange={e=>setSource(e.target.value)}><option value="all">Both Town feeds</option><option value="prcr">Parks & Recreation</option><option value="arts">Arts Center</option></select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>{(query||source!=='all'||from||to)&&<button onClick={()=>{setQuery('');setSource('all');setFrom('');setTo('');}}>Clear filters</button>}</section>
 <div className="list-title"><h2 tabIndex={-1}>{tab}</h2><span>{visible.length} matching {visible.length===1?'item':'items'} · ranked by stated interests</span></div>
 <section className="event-list" aria-label={`${tab} events`}>{visible.map(item=><article className="event" key={item.id} data-event-id={item.id}><div className="date-col"><strong>{item.start.local?new Date(`${item.start.local.slice(0,10)}T12:00:00Z`).toLocaleString('en-US',{month:'short',timeZone:'UTC'}):'?'}</strong><span>{item.start.local?.slice(8,10)??'—'}</span></div><div className="event-body"><div className="event-labels"><span>{item.memberships.map((p:string)=>p==='arts'?'Arts Center':'Parks & Recreation').join(' · ')}</span><span>{item.kind==='archived'?'Archived Oct 3 snapshot':'Locally checked '+shortDate(item.observedAt)+' ET'}</span></div><button className="title-button" onClick={()=>showDetails(item)}>{item.title}</button><p className="event-time">{dateTime(item.start)}{item.location?' · '+item.location:''}</p><p className="excerpt">{item.description.replace(/https?:\/\/\S+/g,'').slice(0,190)}</p><div className="event-labels"><span className="badge">{item.closure?'Closure notice':item.verdict}</span>{item.reasons.length>0?<span>Matches {item.reasons.map((r:any)=>r.key).join(', ')}</span>:<span>No stated interest match</span>}{item.verdict==='ineligible'&&<span>Excluded: {item.rules.filter((r:any)=>r.result==='fail').map((r:any)=>r.reason).join(' ')}</span>}{item.conflict&&<span>Feed disagreement</span>}{item.unread&&<span>Unreviewed version {item.version}</span>}{item.passed&&<span className="pass-label">Passed: {item.decision.active.payload.reasons.map((r:ReasonCode)=>REASONS[r]).join(' · ')}{item.decision.active.snapshot.decisionScope==='program'||item.recurring?' · Individual dates need checking':''}</span>}</div></div><div className="row-actions"><button className={item.interested?'saved':''} onClick={()=>action(item,'interested',!item.interested)}>{item.passed?(item.interested?'Saved ✓':'Save bookmark'):(item.interested?'Interested ✓':'Interested')}</button>{item.passed?<button disabled={decisionBusy||Boolean(reasonForm)} onClick={()=>decide(item,'undo')}>Undo pass</button>:<button disabled={decisionBusy} onClick={()=>openPass(item)}>Not interested</button>}<button onClick={()=>action(item,'hidden',!item.hidden)}>{item.hidden?'Restore':'Hide'}</button><button onClick={()=>showDetails(item)}>Details →</button></div></article>)}{visible.length===0&&<div className="empty"><h3>No items in this view.</h3><p>Try another view or clear the filters. Source coverage remains unknown.</p></div>}</section></>}
 <footer>Private local preview · New York event times · Original public source text retained as evidence</footer>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><section className="detail" role="dialog" aria-modal="true" aria-labelledby="detail-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close details" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">VERSION {selected.version} · {selected.kind==='archived'?'ARCHIVED EVIDENCE':'LOCAL RETRIEVAL'}</span><h2 id="detail-title">{selected.title}</h2>{latestSelectedVersion>selected.version&&<p className="decision-warning">Newer source version {latestSelectedVersion} exists. This dialog still shows version {selected.version}; close and reopen to inspect the newer facts.</p>}{decisionError&&<p className="decision-warning" role="alert">{decisionError}</p>}<p>{dateTime(selected.start)}</p><p>Ends: {dateTime(selected.end)}{selected.end.kind==='all-day'?' (exclusive end date)':''}</p>{selected.location&&<p>{selected.location}</p>}<p className="full-description">{selected.description}</p>{selected.detailUrl?<a className="official" href={selected.detailUrl} target="_blank" rel="noopener noreferrer">Open official listing ↗</a>:<p>No verified official detail link supplied.</p>}<p className="footnote">Verify age, fee, signup and capacity on the official listing. A link click is not registration.</p><h3 id="decision-heading" tabIndex={-1}>Your decision</h3>{selected.passed?<div className="decision-summary"><strong>{selected.interested?'Saved bookmark · passed':'Passed'}</strong><ul>{selected.decision.active.payload.reasons.map((r:ReasonCode)=><li key={r}>{REASONS[r]}</li>)}</ul>{selected.decision.active.payload.dimensions.length>0&&<p>Concern: {selected.decision.active.payload.dimensions.join(', ')}</p>}<p>{selected.decision.active.payload.generalIntent==='generally'?`General preference intent: ${selected.decision.active.snapshot.target.label} · ${selected.decision.active.payload.targetScope==='child'?'selected child':'household'}`:'Applies to this listing only; no general preference inferred.'}</p>{selected.decision.active.payload.note&&<p className="private-note">Your optional local note: {selected.decision.active.payload.note}</p>}<p className="footnote">Shown source version {selected.decision.active.snapshot.sourceVersion} · {selected.decision.active.snapshot.limitations} Ranking is unchanged.</p>{selected.recurring&&selected.decision.active.snapshot.decisionScope!=='program'&&<p>Current listing: unsupported recurring program. Individual dates need checking; the original pass retains its earlier single-event scope.</p>}<button disabled={decisionBusy||Boolean(reasonForm)} onClick={()=>decide(selected,'undo')}>Undo this pass</button><button disabled={decisionBusy||Boolean(reasonForm)} onClick={()=>openPass(selected)}>Change reasons</button></div>:<p>No current pass. Bookmarking, Hide and source review are separate actions.</p>}
 {selected.decision.reconsider&&<div className="reconsider-panel"><h3>{selected.decision.reconsider.primary?'Reconsider timing':'Other attendance change'}</h3><p>{selected.decision.reconsider.reason} Your original decision remains active.</p>{selected.decision.reconsider.differences.map((d:any,n:number)=><div className="attendance-difference" key={n}><strong>{d.source in PARTS?PARTS[d.source as keyof typeof PARTS].name:d.source} · {d.field}</strong><p>Earlier: {attendanceValue(d.field,d.before)}</p><p>Now: {attendanceValue(d.field,d.after)}</p></div>)}{selected.decision.reconsider.scopeChanged&&<p>The source’s recurrence scope changed. The original decision retains its original scope.</p>}{selected.decision.reconsider.programLevel&&<p>Program-level schedule only. Individual dates need checking.</p>}<button disabled={decisionBusy} onClick={()=>decide(selected,'reconsider_review')}>Mark reconsideration seen</button><p className="footnote">This does not undo the pass, mark the source reviewed or acknowledge a source warning.</p></div>}
 {reasonForm&&<form className="reason-form" onSubmit={e=>{e.preventDefault();decide(selected,'pass',reasonForm);}}><h3>Not interested — why?</h3><p>Select at least one reason. Multiple reasons are welcome; a note is optional.</p><fieldset disabled={decisionBusy}><legend>Reason categories</legend>{Object.entries(REASONS).map(([code,label])=><label className="checkbox" key={code}><input type="checkbox" checked={reasonForm.reasons.includes(code)} onChange={e=>setReasonForm({...reasonForm,reasons:e.target.checked?[...reasonForm.reasons,code]:reasonForm.reasons.filter((r:string)=>r!==code)})}/>{label}</label>)}</fieldset>
 {reasonForm.reasons.includes('general')&&<fieldset disabled={decisionBusy}><legend>What should this mean?</legend><label className="checkbox"><input type="radio" name="general-intent" value="listing" checked={reasonForm.generalIntent==='listing'} onChange={()=>setReasonForm({...reasonForm,generalIntent:'listing'})}/>Just this listing (default)</label><label className="checkbox"><input type="radio" name="general-intent" value="generally" checked={reasonForm.generalIntent==='generally'} onChange={()=>setReasonForm({...reasonForm,generalIntent:'generally'})}/>Generally — choose one topic or aspect</label>{reasonForm.generalIntent==='generally'&&<><label>Topic or aspect<select value={reasonForm.targetId} onChange={e=>setReasonForm({...reasonForm,targetId:e.target.value})}><option value="">Choose a topic or aspect</option>{selected.groundedFeatures.map((f:any)=><option key={f.id} value={f.id}>{f.label} · source says “{f.quote}”</option>)}</select></label>{selected.groundedFeatures.length===0&&<p>This listing has no supported topic or aspect to select. Choose just this listing or add a note.</p>}<label>Preference intent scope<select value={reasonForm.targetScope} onChange={e=>setReasonForm({...reasonForm,targetScope:e.target.value})}><option value="child">Selected child</option><option value="household">Household</option></select></label></>}<p className="footnote">Only the selected aspect is recorded. This phase records scoped intent; ranking and settings do not change.</p></fieldset>}
 {reasonForm.reasons.includes('concern')&&<fieldset disabled={decisionBusy}><legend>Which concern?</legend>{CONCERN_DIMENSIONS.map(d=><label className="checkbox" key={d}><input type="checkbox" checked={reasonForm.dimensions.includes(d)} onChange={e=>setReasonForm({...reasonForm,dimensions:e.target.checked?[...reasonForm.dimensions,d]:reasonForm.dimensions.filter((x:string)=>x!==d)})}/>{d}</label>)}<p className="footnote">This listing only. No general price, travel or organizer rule is created.</p></fieldset>}
 {(reasonForm.reasons.includes('timing')||reasonForm.reasons.includes('conflict'))&&<p>{selected.recurring?'Program-level pass against the displayed schedule. Individual dates need checking; no meetings or recurring calendar constraint are invented.':'Timing applies to this event only; it creates no repeating schedule constraint.'}</p>}
 <label>Optional note (kept on this computer)<textarea maxLength={2000} value={reasonForm.note} disabled={decisionBusy} onChange={e=>setReasonForm({...reasonForm,note:e.target.value})}/></label><div className="detail-actions"><button type="submit" className="primary" disabled={decisionBusy||!reasonForm.reasons.length||(reasonForm.reasons.includes('general')&&reasonForm.generalIntent==='generally'&&!reasonForm.targetId)||(reasonForm.reasons.includes('concern')&&!reasonForm.dimensions.length)}>{decisionBusy?'Saving…':'Pass with these reasons'}</button><button type="button" disabled={decisionBusy} onClick={()=>setReasonForm(null)}>Cancel</button></div></form>}
 {selected.legacyFeedback.length>0&&<p className="footnote">Earlier More / Less: {selected.legacyFeedback.map((f:any)=>f.direction).join(', ')}. Preserved as unscoped history; no reasons, child targets or general preferences have been invented.</p>}
 {selected.decision.history.length>0&&<details className="decision-audit"><summary>Decision history ({selected.decision.history.length})</summary>{selected.decision.history.map((d:any)=><p key={d.decision_id}>{d.action==='pass'?'Passed':d.action==='undo'?'Undo linked pass':'Reconsideration seen'} · version {d.snapshot.sourceVersion} · {shortDate(d.created_at)} ET{d.action==='pass'?` · ${d.payload.reasons.map((r:ReasonCode)=>REASONS[r]).join(', ')}`:''}</p>)}</details>}
 <h3>Why it appears</h3>{selected.reasons.length?selected.reasons.map((r:any)=><p key={r.key}>{r.key} · weight {r.weight} · source mentions “{r.evidence}”</p>):<p>No matching preference words. You can still inspect this item.</p>}<h3>Rules & uncertainty</h3>{selected.rules.map((r:any)=><div className="rule" key={r.name}><strong>{r.name}: {r.result}</strong><p>{r.reason}</p></div>)}{selected.timeWarnings.map((w:string)=><p key={w}>{w}</p>)}{selected.sourceStampWarnings.map((w:string)=><p className="footnote" key={w}>{w}</p>)}<h3>Source evidence</h3>{selected.representations.map((r:any)=><p key={r.part}>{PARTS[r.part as keyof typeof PARTS].name} · {r.kind} · {shortDate(r.observed_at)} ET</p>)}{selected.conflict&&<><h3>Conflicting category representations</h3><p>The feeds disagree. Both are shown below; the main display uses a stable category order and does not establish authoritative facts.</p>{selected.variants.map((v:any,n:number)=><pre key={n}>{JSON.stringify(v,null,2)}</pre>)}</>}<h3>Changes</h3><p className="footnote">A change in one feed can be a warning even when another feed disagrees. It does not establish cancellation or a schedule for the whole event.</p>{selected.changes.length?selected.changes.map((c:any)=><div className="change" key={c.change_id}><strong>Version {c.version} · {c.cause==='parser'?'Parser correction · ':''}{c.fields.join(', ')} {c.ack_at?'· reviewed':''}</strong>{c.fields.filter((f:string)=>f in c.after).map((f:string)=><p key={f}><b>{f}</b><span>Before: {typeof c.before[f]==='object'?JSON.stringify(c.before[f]):String(c.before[f])}</span><span>After: {typeof c.after[f]==='object'?JSON.stringify(c.after[f]):String(c.after[f])}</span></p>)}</div>):<p>Initial collection. Publication time is unknown.</p>}<p className="footnote">Observed {shortDate(selected.observedAt)} ET · First seen {shortDate(selected.firstSeen)} ET · UID {selected.uid}</p><div className="detail-actions"><button onClick={()=>action(selected,'interested',!selected.interested)}>{selected.interested?'Unsave bookmark':selected.passed?'Save bookmark':'Interested'}</button>{!reasonForm&&<button disabled={decisionBusy} onClick={()=>openPass(selected)}>{selected.passed?'Change pass reasons':'Not interested'}</button>}<button onClick={()=>action(selected,'hidden',!selected.hidden)}>{selected.hidden?'Restore':'Hide'}</button></div><button className="primary review" onClick={()=>action(selected,'review',{version:selected.version,changeIds:selected.changes.filter((c:any)=>!c.ack_at).map((c:any)=>c.change_id)})}>Review version {selected.version} and these changes</button></section></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
